<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestingDemoTestsuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>22f25fda-eee6-422c-b116-9a720bbb84e5</testSuiteGuid>
   <testCaseLink>
      <guid>5ec8b5ce-7aa9-489c-9800-d554e2540d7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CountryInfoTests/test_data_driven_demo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>555c5c2f-458c-4b88-a732-9e96d7e4a201</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CountryTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>555c5c2f-458c-4b88-a732-9e96d7e4a201</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryCode</value>
         <variableId>79d327bc-b5eb-4cf3-8cc3-f0e655166c06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>555c5c2f-458c-4b88-a732-9e96d7e4a201</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Capital</value>
         <variableId>54db34e0-7a6c-4e96-a42a-659836e3de71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>555c5c2f-458c-4b88-a732-9e96d7e4a201</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Currency1</value>
         <variableId>2e205d60-35ff-42d4-a13d-7cdf34e94153</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
